
import Thumbnail1 from "./assets/blog1.jpg"
import Thumbnail2 from "./assets/blog2.jpg"
import Thumbnail3 from "./assets/blog3.jpg"
import Thumbnail4 from "./assets/blog4.jpg"

export const Dummy_Posts =[
    {
        id: "1",
        thumbnail: Thumbnail1,
        category: "education",
        title: "Here is the title of this post",
        desc:' Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt suscipit fugiat rerum doloribus autem natus atque magnam non a dolor esse in, nobis ipsum quod eligendi totam tempora! Aliquam mollitia magni aut alias id earum quibusdam iusto vel optio sed, quidem veritatis saepe nesciunt temporibus nam voluptates sequi? Dolor expedita assumenda odio officiis nemo ratione corrupti alias possimus. Minus eveniet expedita accusamus est harum perferendis non sunt sit, soluta illum ullam voluptatum, quaerat nisi nam quasi! Dignissimos rem, inventore quidem quae saepe fugit asperiores libero incidunt sequi iure eaque nobis consequatur provident, voluptates hic dolore. Neque deleniti quod enim consectetur aliquam possimus odit quidem aut eligendi aperiam cum eveniet dolore error distinctio ducimus labore, eos incidunt! Nisi eligendi consequatur cupiditate, facilis quibusdam illo? Quia, quam. Est commodi mollitia repudiandae earum id nemo explicabo, sit adipisci perferendis iusto voluptatem neque provident officia aliquam amet molestias esse nesciunt sunt? Asperiores, assumenda, temporibus omnis, quisquam fugit inventore quas fugiat dolorum hic quos a ratione iusto consequuntur harum quasi amet architecto culpa maiores delectus alias minus impedit adipisci soluta nemo. Odit illo distinctio possimus rerum, et sint a ipsa ab aspernatur, aut repudiandae cumque reiciendis voluptatibus aperiam! In minus, asperiores nihil a aspernatur magnam sit similique vitae voluptas voluptatibus voluptates magni dolorem debitis, suscipit id quod natus quo pariatur nostrum facere provident ipsa architecto excepturi. Ipsa odio similique, animi porro dicta quae quia quaerat tempore voluptatem placeat quasi assumenda deserunt nihil voluptate officiis adipisci ipsum doloribus velit amet aliquid distinctio. Delectus atque hic nostrum magnam, asperiores quaerat debitis quisquam exercitationem sequi facilis dolores molestias illo, aut tenetur in optio, commodi quo. Ab, voluptatum omnis! Exercitationem sequi quam doloremque. Nisi eos facere hic expedita pariatur perferendis qui iusto laboriosam, error impedit ut doloribus ipsam dignissimos numquam, aliquam vitae vel mollitia officia consequuntur unde corrupti quas.',
        authorID: 3
    },
    {
        id: "2",
        thumbnail: Thumbnail2,
        category: "science",
        title: "Here is the title of this post",
        desc:' Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt suscipit fugiat rerum doloribus autem natus atque magnam non a dolor esse in, nobis ipsum quod eligendi totam tempora! Aliquam mollitia magni aut alias id earum quibusdam iusto vel optio sed, quidem veritatis saepe nesciunt temporibus nam voluptates sequi? Dolor expedita assumenda odio officiis nemo ratione corrupti alias possimus. Minus eveniet expedita accusamus est harum perferendis non sunt sit, soluta illum ullam voluptatum, quaerat nisi nam quasi! Dignissimos rem, inventore quidem quae saepe fugit asperiores libero incidunt sequi iure eaque nobis consequatur provident, voluptates hic dolore. Neque deleniti quod enim consectetur aliquam possimus odit quidem aut eligendi aperiam cum eveniet dolore error distinctio ducimus labore, eos incidunt! Nisi eligendi consequatur cupiditate, facilis quibusdam illo? Quia, quam. Est commodi mollitia repudiandae earum id nemo explicabo, sit adipisci perferendis iusto voluptatem neque provident officia aliquam amet molestias esse nesciunt sunt? Asperiores, assumenda, temporibus omnis, quisquam fugit inventore quas fugiat dolorum hic quos a ratione iusto consequuntur harum quasi amet architecto culpa maiores delectus alias minus impedit adipisci soluta nemo. Odit illo distinctio possimus rerum, et sint a ipsa ab aspernatur, aut repudiandae cumque reiciendis voluptatibus aperiam! In minus, asperiores nihil a aspernatur magnam sit similique vitae voluptas voluptatibus voluptates magni dolorem debitis, suscipit id quod natus quo pariatur nostrum facere provident ipsa architecto excepturi. Ipsa odio similique, animi porro dicta quae quia quaerat tempore voluptatem placeat quasi assumenda deserunt nihil voluptate officiis adipisci ipsum doloribus velit amet aliquid distinctio. Delectus atque hic nostrum magnam, asperiores quaerat debitis quisquam exercitationem sequi facilis dolores molestias illo, aut tenetur in optio, commodi quo. Ab, voluptatum omnis! Exercitationem sequi quam doloremque. Nisi eos facere hic expedita pariatur perferendis qui iusto laboriosam, error impedit ut doloribus ipsam dignissimos numquam, aliquam vitae vel mollitia officia consequuntur unde corrupti quas.',
        authorID: 1
    },
    {
        id: "3",
        thumbnail: Thumbnail3,
        category: "weather",
        title: "Here is the title of this post",
        desc:' Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt suscipit fugiat rerum doloribus autem natus atque magnam non a dolor esse in, nobis ipsum quod eligendi totam tempora! Aliquam mollitia magni aut alias id earum quibusdam iusto vel optio sed, quidem veritatis saepe nesciunt temporibus nam voluptates sequi? Dolor expedita assumenda odio officiis nemo ratione corrupti alias possimus. Minus eveniet expedita accusamus est harum perferendis non sunt sit, soluta illum ullam voluptatum, quaerat nisi nam quasi! Dignissimos rem, inventore quidem quae saepe fugit asperiores libero incidunt sequi iure eaque nobis consequatur provident, voluptates hic dolore. Neque deleniti quod enim consectetur aliquam possimus odit quidem aut eligendi aperiam cum eveniet dolore error distinctio ducimus labore, eos incidunt! Nisi eligendi consequatur cupiditate, facilis quibusdam illo? Quia, quam. Est commodi mollitia repudiandae earum id nemo explicabo, sit adipisci perferendis iusto voluptatem neque provident officia aliquam amet molestias esse nesciunt sunt? Asperiores, assumenda, temporibus omnis, quisquam fugit inventore quas fugiat dolorum hic quos a ratione iusto consequuntur harum quasi amet architecto culpa maiores delectus alias minus impedit adipisci soluta nemo. Odit illo distinctio possimus rerum, et sint a ipsa ab aspernatur, aut repudiandae cumque reiciendis voluptatibus aperiam! In minus, asperiores nihil a aspernatur magnam sit similique vitae voluptas voluptatibus voluptates magni dolorem debitis, suscipit id quod natus quo pariatur nostrum facere provident ipsa architecto excepturi. Ipsa odio similique, animi porro dicta quae quia quaerat tempore voluptatem placeat quasi assumenda deserunt nihil voluptate officiis adipisci ipsum doloribus velit amet aliquid distinctio. Delectus atque hic nostrum magnam, asperiores quaerat debitis quisquam exercitationem sequi facilis dolores molestias illo, aut tenetur in optio, commodi quo. Ab, voluptatum omnis! Exercitationem sequi quam doloremque. Nisi eos facere hic expedita pariatur perferendis qui iusto laboriosam, error impedit ut doloribus ipsam dignissimos numquam, aliquam vitae vel mollitia officia consequuntur unde corrupti quas.',
        authorID: 13
    },
    {
        id: "4",
        thumbnail: Thumbnail4,
        category: "farming",
        title: "Here is the title of this post click on title to open",
        desc:' Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt suscipit fugiat rerum doloribus autem natus atque magnam non a dolor esse in, nobis ipsum quod eligendi totam tempora! Aliquam mollitia magni aut alias id earum quibusdam iusto vel optio sed, quidem veritatis saepe nesciunt temporibus nam voluptates sequi? Dolor expedita assumenda odio officiis nemo ratione corrupti alias possimus. Minus eveniet expedita accusamus est harum perferendis non sunt sit, soluta illum ullam voluptatum, quaerat nisi nam quasi! Dignissimos rem, inventore quidem quae saepe fugit asperiores libero incidunt sequi iure eaque nobis consequatur provident, voluptates hic dolore. Neque deleniti quod enim consectetur aliquam possimus odit quidem aut eligendi aperiam cum eveniet dolore error distinctio ducimus labore, eos incidunt! Nisi eligendi consequatur cupiditate, facilis quibusdam illo? Quia, quam. Est commodi mollitia repudiandae earum id nemo explicabo, sit adipisci perferendis iusto voluptatem neque provident officia aliquam amet molestias esse nesciunt sunt? Asperiores, assumenda, temporibus omnis, quisquam fugit inventore quas fugiat dolorum hic quos a ratione iusto consequuntur harum quasi amet architecto culpa maiores delectus alias minus impedit adipisci soluta nemo. Odit illo distinctio possimus rerum, et sint a ipsa ab aspernatur, aut repudiandae cumque reiciendis voluptatibus aperiam! In minus, asperiores nihil a aspernatur magnam sit similique vitae voluptas voluptatibus voluptates magni dolorem debitis, suscipit id quod natus quo pariatur nostrum facere provident ipsa architecto excepturi. Ipsa odio similique, animi porro dicta quae quia quaerat tempore voluptatem placeat quasi assumenda deserunt nihil voluptate officiis adipisci ipsum doloribus velit amet aliquid distinctio. Delectus atque hic nostrum magnam, asperiores quaerat debitis quisquam exercitationem sequi facilis dolores molestias illo, aut tenetur in optio, commodi quo. Ab, voluptatum omnis! Exercitationem sequi quam doloremque. Nisi eos facere hic expedita pariatur perferendis qui iusto laboriosam, error impedit ut doloribus ipsam dignissimos numquam, aliquam vitae vel mollitia officia consequuntur unde corrupti quas.',
        authorID: 11
    },
]



